version: "3"

services:
  backend:
    container_name: kapan_server
    build:
      context: .
      dockerfile: Dockerfile
    mem_limit: 256m
    cpus: 1
    ports:
      - 8080:8080
    environment:
      - NODE_ENV=production
